#配置端口号
server:
  port: 8083

  #数据库配置
spring:
  datasource:
    name: mall_datasource
    url: jdbc:mysql://192.168.142.129:3306/imooc_mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: St1282001316*
    driver-class-name: com.mysql.cj.jdbc.Driver
    #开启热部署
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  redis:
    host: 192.168.142.129
    port: 6380
    password: 123456

file:
  upload:
    dir: E:/IdeaProjects/mall/src/main/java/pictures/
    ip: 127.0.0.1

mybatis:
  mapper-locations: classpath:mappers/*.xml
