#配置端口号
server:
  port: 8080

  #数据库配置
spring:
  datasource:
    name: mall_datasource
    url: jdbc:mysql://127.0.0.1:3306/imooc_mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: St1282001316*
    driver-class-name: com.mysql.cj.jdbc.Driver
    #开启热部署
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  redis:
    host: localhost
    port: 6379
    password:

file:
  upload:
    dir: /root/images/
    ip: 112.126.63.142

mybatis:
  mapper-locations: classpath:mappers/*.xml
